include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Prefer const constructors
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    
    # Prefer final fields
    prefer_final_fields: true
    prefer_final_locals: true
    
    # Avoid unnecessary containers
    avoid_unnecessary_containers: true
    
    # Prefer sized box over container
    prefer_sized_box: true
    
    # Use proper async/await
    avoid_print: true
    prefer_typing_uninitialized_variables: true
    
    # Naming conventions
    camel_case_types: true
    camel_case_extensions: true
    file_names: true
    
    # Code organization
    directives_ordering: true
    sort_child_properties_last: true
    
    # Error handling
    avoid_catches_without_on_clauses: true
    avoid_catching_errors: true
    
    # Performance
    avoid_web_libraries_in_flutter: true
    use_build_context_synchronously: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated/**"
  
  errors:
    invalid_annotation_target: ignore 